### ISSUE TITLE
Fallback to '/' does not work

### ISSUE THREAD

**Issue by Matheus-Garbelini** [thorny-thorny/vuepress-offlinify#3]
Hi, thanks a lot for this project. However, it seems when using '/' on the sidebar, vuepress redirects to / which then breaks navigation. 
Here an example of a configuration that is not working correctly for me.
To test this you need to create some dummy files (`architecture.md` and `stacks.md`)
```javascript
const { description } = require('../../package')



module.exports = {
    /**
     * Ref：https://v1.vuepress.vuejs.org/config/#title
     */
    title: 'test',
    dest: './release/docs',
    base: '' || process.env['VUEPRESS_BASE_URL'],
    /**
     * Ref：https://v1.vuepress.vuejs.org/config/#description
     */
    description: description,

    /**
     * Extra tags to be injected to the page HTML `<head>`
     *
     * ref：https://v1.vuepress.vuejs.org/config/#head
     */
    head: [
        ['meta', { name: 'theme-color', content: '#3eaf7c' }],
        ['meta', { name: 'apple-mobile-web-app-capable', content: 'yes' }],
        ['meta', { name: 'apple-mobile-web-app-status-bar-style', content: 'black' }]
    ],

    /**
     * Theme configuration, here is the default theme configuration for VuePress.
     *
     * ref：https://v1.vuepress.vuejs.org/theme/default-theme-config.html
     */
    themeConfig: {
        repo: '',
        repoLabel: 'Repository',
        editLinks: false,
        docsDir: 'docs',
        editLinkText: '',
        lastUpdated: true,
        nav: [{
                text: 'Getting Started',
                link: '/guide',
            },
            {
                text: 'Topics',
                items: [
                    { text: 'Architecture', link: '/architecture' },
                    { text: 'Protocol Stacks', link: '/stacks' },
                ]
            },
            {
                text: 'GreyHound',
                link: '/old_greyhound/index.html',
                target:'_blank'
            },
        ],
        sidebar: {
            '/': [{
                title: 'Topics',
                initialOpenGroupIndex: 0,
                sidebarDepth: 1,
                collapsable: false,
                children: [
                    '', /* index.md */
                    'guide',
                    'architecture',
                ]
            }],
        }
    },

    /**
     * Apply plugins，ref：https://v1.vuepress.vuejs.org/plugin/
     */
    plugins: [
        '@vuepress/plugin-back-to-top',
        '@vuepress/plugin-medium-zoom',
    ]
}
```

**Comment by thorny-thorny** [comment]
Hi Matheus!
1. What vuepress version do you use? I tested only version 1.5.1
2. The script isn't aware of custom `dest` setting, are you sure you modified script properly? What output does it give? It should be smth like that
```Page offlinified: 404.html
Page offlinified: architecture.html
Page offlinified: guide.html
Page offlinified: index.html
Page offlinified: stacks.html
Style offlinified: 0.styles.37c174a0.css
Script offlinified: 2.145243f9.js
Script offlinified: app.4b748328.js
```
3. Are you sure there's nothing in the `process.env['VUEPRESS_BASE_URL']`? Values other than `''` or `undefined` for `base` seems to break the script rewriting patterns
4.  "vuepress redirects to /" from where? Can you describe steps to reproduce?
5. If "vuepress redirects to /" then the browser should display "Index of" page with list of local files. Are you sure you open files locally, not via a webserver?
6. I tried your config with some dummy files and it works fine [fallback-issue.zip](https://github.com/thorny-thorny/vuepress-offlinify/files/5769315/fallback-issue.zip)

**Comment by Matheus-Garbelini** [comment]
Hi @thorny-thorny, my **vuepress version is 1.7.1** and my **NodeJS version is v12.20.0**. 
I only use the VUEPRESS_BASE_URL on remote deployment, so it should always be '' for my local build. 

Let me send you my complete environment so you can easily test it:
~~(redacted)~~

In short, you can replicate the issue running the following:
```shell
node install
npm run build
node offlinify.js docs
```
**Note: my package-lock.json is there so you can see the exact versions I'm using, but feel free to delete it if you have any nodejs version conflict**

My output is as follows:
![Screenshot_20210105_205008](https://user-images.githubusercontent.com/6465668/103648544-01dfce80-4f98-11eb-9a3c-1852c75585df.png)


As soon as I open the index.html at `docs/.vuepress/dist/index.html` with chrome or firefox, it redirects me to `file:///` with the `index of` page you described (The working directory when I left click to open with chrome or firefox should be at docs/.vuepress/dist/).
It appear there is some dynamic redirecting from the vue router in the new vuepress version?

**Update 1:** I've fixed my package.json to vuepress 1.5.1 but the same happens. If your build is successful I can test your build on my chrome / firefox so we can narrow down what could be the issue.
My Chrome version: Version 87.0.4280.66 (Official Build) (64-bit)

**Update 2:** I've tried your compiled fallback-issue.zip, but the following shows on my chrome and firefox:
(It's trying to load /assets from memes.com :smile: ?)
![Screenshot_20210105_210118](https://user-images.githubusercontent.com/6465668/103649288-2daf8400-4f99-11eb-9c91-178def5f9d1f.png)

**Comment by thorny-thorny** [comment]
> It's trying to load /assets from memes.com 😄 ?

Lol yeah i was checking `base`, it's wrong archive. This issue happened because of minified JS variation. It should work for now, both 1.5.1 and 1.7.1 seems to be OK.

**Comment by Matheus-Garbelini** [comment]
@thorny-thorny thanks a lot. Really liked your energy. 
It works now. Regards.
